services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
